### PR TITLE
Improvements to feed items

### PR DESCRIPTION
**Pull request by Schmiddiii**
# Licensing 

- [x] I confirm that this is either my code or was released under the terms of a GPLv3-or-later compatible license. Also I agree to release it here under the terms of the GPLv3-or-later.

# Description

Improvements to the feed item. I basically made everything rounder and also fixed the thumbnail changing size when the title has two lines.

# Linked Issue

Relates to #95.

### CODE REVIEW

**Comment by Schmiddiii** [comment]
I have not yet worked on improving the "playing" and "downloading" indicators. I guess a `GtkOverlay` would be bes for that?

**Comment by TheEvilSkeleton** [comment]
This looks so much better!

I think an AdwActionRow-like widget would fit better here, as it has some sort of implementation of max-width and light gray foreground.

**Comment by Schmiddiii** [comment]
I now added an overlay to the image when playing. This looks so much better already.

I have also claped the max width for the videos using `AdwClamp` (with the default settings for now). I am not sure what light-gray foreground you mean, to me the videos-page looks pretty similar in terms of colors to the settings (which is using superclasses of `AdwPreferencesRow`s which all have the same styling).

**Comment by TheEvilSkeleton** [comment]
> I am not sure what light-gray foreground you mean

Sorry, I'll try to explain it better. In Tubefeeder, each row looks like this: 
image

The background color of the _row_ is `#1e1e1e`. However, if we use GNOME Settings as an example, each row looks like this:

image

The background color of the row is `#363636` instead. So, I'm suggesting that the background color of each row should be `#363636` instead of `#1e1e1e`. Does that make more sense?

---

Visually, it looks a lot better already.

There are some problems I've encountered:

1. The blue border goes outside of corners: 
image
2. The scrollbar is in the middle and not at the far right: 
image

**Comment by Schmiddiii** [comment]
> The background color of the row is #363636 instead. So, I'm suggesting that the background color of each row on Tubefeeder should be #363636 instead of #1e1e1e. Does that make more sense?

This is pretty weird. The color you mentioned is defined in `libadwaita` to be used for widgets with classes `tab-page-color-8` (see [here](https://gitlab.gnome.org/search?search=363636&nav_source=navbar&project_id=14079&group_id=8&search_code=true&repository_ref=main)). Neither the color nor the widget class seem to be used in libadwaita or Settings (see [here](https://gitlab.gnome.org/search?search=tab-page-color-8&nav_source=navbar&project_id=14079&group_id=8&search_code=true&repository_ref=main), [here](https://gitlab.gnome.org/search?search=tab-page-color-8&nav_source=navbar&project_id=660&group_id=8&search_code=true&repository_ref=main) and [here](https://gitlab.gnome.org/search?search=363636&nav_source=navbar&project_id=660&group_id=8&search_code=true&repository_ref=main)), it is also not named in the [Adwaita named colors](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1.0.0/named-colors.html). Are you using some theme? Could you try again with Adwaita Light?

> The blue border goes outside of corners

I assume you are talking about the border of the overlay over the image? It is hard to see with the small resolution.

This is also weird. The inspector says that the picture has a rounded border of `12pt` (something that can also be found in [libadwaita](https://gitlab.gnome.org/GNOME/libadwaita/-/blob/main/src/stylesheet/_common.scss#L8)), but setting the border radius of osd in the inspector yields obvious wrong results. I therefore just eyeballed it, and seem to have gotten it wrong. But I have also check other values and found none that completely work.

For reference, the custom CSS to be used in the inspector:

```css
.osd {
	border-radius: 12pt;
}
```

**Comment by Schmiddiii** [comment]
> Sorry, I completely forgot to mention that I picked up the colors using [Color Picker](https://beta.flathub.org/apps/nl.hjdskes.gcolor3) - I don't know if these are the actual colors.

You could open the GTK inspector (Ctlr-Shift+D), click on the row, check the CSS properties and find the background color. But normally I would guess that the color picker would return the correct results.

> Yes. When you press tab and then click one of the rows, you'll see the blue outline. Here's a better picture:

This is actually not the outline I was talking about (I was talking about the overlay of the image going a little bit outside the image).

**Comment by Schmiddiii** [comment]
I have now figured out why the color was not working. By default, the feed-list had a class of `view` (as it is a `ListView`). Normally, using the `card`-class overwrites the background color to be like you mentioned, but it seems that for some reason the `view` color had priority. I manually changed the color of the view to match the color of a `card` in the custom CSS.

**Comment by TheEvilSkeleton** [comment]
It looks a lot better now ^^

There are some issues I've noticed:

1. When fully expanded, there's an empty row, and empty space:
    image
1. When there isn't enough space to list everything, the "Load More" button overlaps:
    image
1. This is likely nit picky, but hovering and leaving the cursor doesn't fade. Here's GNOME Settings (top) as a reference, compared to Tubefeeder (bottom):

[Screencast from 2023-04-04 13-57-46.webm](https://user-images.githubusercontent.com/50847364/229878646-e2cc4436-d586-4c87-b6ba-fbfa47212631.webm)

**Comment by Schmiddiii** [comment]
I should have now fixed points 1, 2 and 4. For the first two, I had to turn off `can-shrink` of the image which may lead to bad behavior if the loaded image is bigger.

> Now, the corner overlaps

You mean in the screenshot the top-left having a slightly darker corner? I cannot reproduce this locally.

**Comment by TheEvilSkeleton** [comment]
> > Now, the corner overlaps
> 
> You mean in the screenshot the top-left having a slightly darker corner? I cannot reproduce this locally.

Yes, although I'm not sure why you can't reproduce it.

Apparently, for me, point 4 hasn't been addressed. There's still no fading and looks exactly what I posted before.

**Comment by Schmiddiii** [comment]
I think the fading should now be fixed, I accidentally used the wrong CSS class. Nevertheless, it seems to me like this only has an effect on transitioning from the outside to the rows, but not between rows. This may also be just my eyes deceiving me as the transition is pretty fast (200ms, copied from libadwaita).

**Pull request merged**
