### PR TITLE
Improve visualization

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
# Licensing 

- [x] I confirm that this is either my code or was released under the terms of a GPLv3-or-later compatible license. Also I agree to release it here under the terms of the GPLv3-or-later.

# Description

- Improve README
- Add CONTRIBUTING file
- Fix typos
- Improve description of program

**Contributing to translation is missing.**

# Linked Issue

Ref. https://github.com/Tubefeeder/Tubefeeder/issues/95

### CODE REVIEW

**Comment by Schmiddiii** [comment]
Translations can be contributed by PR (like code). The relevant files are in `po`. I think that information will be enough for all people interested to translate to figure it out.

And maybe also add to `CONTRIBUTING.md` a notice to the Matrix channel for quick questions and similar?

Otherwise looking good.

**Comment by TheEvilSkeleton** [comment]
> Translations can be contributed by PR (like code). The relevant files are in `po`. I think that information will be enough for all people interested to translate to figure it out.

I think having Weblate set up would be ideal for translators since it's important to make it appealing for people who are less inclined to using git or GitHub. Typically, translators don't want to go through the source code just to translate. Though I'm not sure how hard it's going to be to setup Weblate so there's not much I can suggest. I'm still going to document the current procedure and promote [Poedit](https://poedit.net/) since it's currently the easiest way.

**Comment by Schmiddiii** [comment]
The problem is that I already use the Weblate libre-tier for another project of mine (the account is not linked with my Github account but with my Gitlab account, but this is probably still not intended). And I think only one project can have a libre-tier per person. So Poedit it is  for now.

**Comment by TheEvilSkeleton** [comment]
@Schmiddiii how does one generate a `.po` file when they want to add a new language?

**Comment by Schmiddiii** [comment]
I think it should just be `msginit --locale=<lang>` in the po-directory (see [here](https://www.gnu.org/software/gettext/manual/gettext.html#Creating)) and adding the language to the `LINGUAS` file.

**Comment by TheEvilSkeleton** [comment]
Thanks. It looks like Poedit guides us through that so I'll use their method.

**Comment by TheEvilSkeleton** [comment]
It should be good to go. Don't forget to squash the commit since the commit history is going to look unpleasing otherwise.

**Pull request merged**
