### PR TITLE
Create it.po

### PR DESCRIPTION
**Pull request by albanobattistella**
# Licensing 

- [x] I confirm that this is either my code or was released under the terms of a GPLv3-or-later compatible license. Also I agree to release it here under the terms of the GPLv3-or-later.

# Description

# Linked Issue

### CODE REVIEW

**Comment by Schmiddiii** [comment]
The file will need to be `po/locale/it/de.schmidhuberj.tubefeeder.po`. I know that this is a unusual structure to most other projects but as I do not use meson, this is the best structure I could have used. 

Otherwise everything looks fine apart from the two minor reviews and I am willing to merge this after the fixes. Thank you.

**Comment by Schmiddiii** [comment]
Do you want to push the corrections or should I merge and do the corrections myself? 

I would also need information on how to contact you when some strings change or are added (should not happen too often). Should I ping you on GitHub or write a E-Mail or similar?

**Comment by albanobattistella** [comment]
> Do you want to push the corrections or should I merge and do the corrections myself?
> 
> I would also need information on how to contact you when some strings change or are added (should not happen too often). Should I ping you on GitHub or write a E-Mail or similar?

Hi,
could you merge this time?
No problem, for ping on GitHub or email.
Thanks.
Albano

**Comment by Schmiddiii** [comment]
This is now merged into master with the necessary fixes. I will wait a few days before releasing in case some easy-to-fix issue pops up so I can do both in one release.

**Pull request merged**
