### PR TITLE
Update it.po

### PR DESCRIPTION
**Pull request by airon90**
# Licensing 

- [x] I confirm that this is either my code or was released under the terms of a GPLv3-or-later compatible license. Also I agree to release it here under the terms of the GPLv3-or-later.

# Description

* Added number and expression about plurals in header
* Translated some keys
* Fixed old keys making the translations shorter
* Fixed translation of "subscription(s)" to just "iscrizione/i"
* Fixed two keys: [Piped](https://github.com/TeamPiped/Piped/) must not be translated, "[Instances](https://github.com/TeamPiped/Piped/wiki/Instances)" is a piece of a link

# Linked Issue

#84

### CODE REVIEW

**Comment by airon90** [comment]
@albanobattistella Please review my changes to your translations ;)

**Comment by albanobattistella** [comment]
> @albanobattistella Please review my changes to your translations ;)

@airon90 there were some mistakes thanks.
but Player and downloader must remain that way.
when revising a translation I do not remove the name of the previous translator but add myself below. ;-)
Thanks for your review.

**Comment by Schmiddiii** [comment]
@airon90 there still seems to be a commit missing that fixes the things you mentioned in the last comment.

**Comment by airon90** [comment]
@Schmiddiii Done :)

**Comment by Schmiddiii** [comment]
Thanks.

**Pull request merged**
