### PR TITLE
💄️ Add symbolic app icon

### PR DESCRIPTION
**Pull request by daudix-UFO**
# Licensing 

- [x] I confirm that this is either my code or was released under the terms of a GPLv3-or-later compatible license. Also I agree to release it here under the terms of the GPLv3-or-later.

# Description

Add a symbolic icon for app

_Instead of this one_

image

### CODE REVIEW

**Comment by Schmiddiii** [comment]
I would put this icon into `packaging` instead of `data/icons` (which is used for icons inside of the application). Otherwise seems good.

I will have to update some packaging after that so that the icon will also be included inside the Flatpak.

**Comment by Schmiddiii** [comment]
It seems that GNOME does not like the icon. Instead of displaying it, it just has a white, filled triange with sharp corners. But when exchanging it with a working icon from other apps, it works correctly. 

I will need to investigate that more, which will probably take some time.

**Comment by daudix-UFO** [comment]
Will do it right now

**Comment by daudix-UFO** [comment]
@Schmiddiii Done! there is new PR

**Pull request merged**
